name: Development Deploy

on:
  push:
    branches:
      - development

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DISCORD_HOOK_URL: ${{ secrets.DISCORD_HOOK_URL }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  development-build:
    name: Build Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Retrieve Certs
      run: |
        ./script/retrieve_certs
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_AUTH: ${{ secrets.GIT_AUTH }}
        GIT_URL: ${{ secrets.GIT_URL }}
        CERTS_KEY: ${{ secrets.CERTS_KEY }}

    - name: Build Development Release
      run: |
        ./script/build_release dev

    - name: Deploy development release to bucket/SHA
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        SOURCE_DIR: 's3out'
        DEST_DIR: '$GITHUB_SHA'

    - name: Deploy development release to bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        SOURCE_DIR: 's3outver'

    - name: Notify Discord on failure
      if: failure()
      run: |
        ./script/message failure

    - name: Notify Discord on completion
      if: success()
      run: |
        ./script/message dev-push
